### ISSUE TITLE
Trace a TorchScript model on Inferentia

### ISSUE THREAD

**Issue by mvidela31** [aws-neuron/aws-neuron-sdk#489]
Hi everybody,

I'm trying to compile some popular intermediate representations of deep learning models on Inferentia, since the current support (Pytorch, Tensorflow, and MXNet) is too restrictive for my use case. Unfortunately, I realized that the ONNX models compilation is not supported anymore. However, I read that the `torch_neuron.trace()` is [apparently analogous](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-guide/neuron-frameworks/pytorch-neuron/api-compilation-python-api.html) to the `torch.jit.trace()` compilation method. So, it is possible to compile a TorchScript model on Inferentia using the AWS Neuron library?

P.S.: I realized that my issue is almost identical to the Issue #451, but that one was not resolved :disappointed:.

**Comment by aws-mvaria** [comment]
Yes, it is possible to compile a TorchScript model on Inferentia via `torch_neuron.trace()`.

Issue #451 yielded an issue due to attempted compilation of a detectron2 model. We have a roadmap item #153 to add support for this class of models since they are currently known to fail compilation.

Are you also trying to compile detectron2, or is there a specific error you are running into?

**Comment by mvidela31** [comment]
Hi @aws-mvaria,

I just wanted to be sure that TorchScript models were supported by Neuron, thanks for the confirmation. Perhaps it could be useful to make this information explicit in the AWS Neuron docs.

Many thanks!
