### ISSUE TITLE
Significant rounding error in FP32 matrix multiplication

### ISSUE THREAD

**Issue by xuanqing94** [aws-neuron/aws-neuron-sdk#604]
Hi, I noticed that the rounding error in matrix multiplication is quite large (about 0.001 in abs). Below is a simply way to reproduce:

```python
import numpy as np
import torch
import torch_xla.core.xla_model as xm

device = xm.xla_device()

##### NUMPY RESULTS
arrays = np.load("./error_array.zip")
array1 = arrays["array1"]
array2 = arrays["array2"]
print(np.dot(array1, array2))

> array([[-0.41686782,  0.3622096 ],
>       [ 0.36004627,  0.70566916]], dtype=float32)

#### XLA RESULTS (matrix - matrix multiplication)
tensor1 = torch.from_numpy(array1).to(device)
tensor2 = torch.from_numpy(array2).to(device)
mm = torch.mm(tensor1, tensor2)
print(mm)
> tensor([[-0.4181,  0.3609],
>         [ 0.3568,  0.7071]], device='xla:1')

#### XLA RESULTS (vector - vector multiplication)
mm = torch.mm(tensor1[:1, :], tensor2[:, :1])
print(mm)
> tensor([[-0.4169]], device='xla:1')
```

Notice the difference in the first element of all results, both numpy and XLA (vector x vector) generates the same result. But XLA (matrix x matrix) generates quite different result. I don't think this is due to rounding error in FP32?

**Comment by xuanqing94** [comment]
[error_array.zip](https://github.com/aws-neuron/aws-neuron-sdk/files/10079869/error_array.zip)

**Comment by awsrjh** [comment]
We will look at this and get back to you.

**Comment by jeffhataws** [comment]
Hi @xuanqing94 ,

Some numerical variation is expected in mixed-precision due to compiled tensor relayout operations. 
Please consult the [mixed-precision guide](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/general/appnotes/neuronx-cc/neuronx-cc-training-mixed-precision.html ) for more details.

I tried your test with different casting options, and find that NEURON_CC_FLAGS="--auto-cast=none" option gives the best match:

```
[[-0.41686893  0.36220926]
 [ 0.36004645  0.7056697 ]]

(some output excluded)

tensor([[-0.4169,  0.3622],
        [ 0.3600,  0.7057]], device='xla:1')

(some output excluded)

tensor([[-0.4169]], device='xla:1')
```

Another option that is better than the default is NEURON_CC_FLAGS="--auto-cast matmult --auto-cast-type fp16" 
```                                         
[[-0.41686893  0.36220926]
 [ 0.36004645  0.7056697 ]]

(some output excluded)

tensor([[-0.4170,  0.3621],
        [ 0.3605,  0.7054]], device='xla:1')

(some output excluded)

tensor([[-0.4169]], device='xla:1')
```

**Comment by xuanqing94** [comment]
Thanks @jeffhataws , that's also my guess.
