### ISSUE TITLE
neuron-cc not supported some operators when compiling

### ISSUE THREAD

**Issue by 3i-MiaHong** [aws-neuron/aws-neuron-sdk#698]
Hi, 
currently I'm trying to compile a pytorch model to torch script using `torch-neuron` (`neuron-cc`).
During that, I met some issues like below.
```
INFO:Neuron:The following operations are currently not supported in torch-neuron for this model:
INFO:Neuron:aten::__or__
INFO:Neuron:aten::clamp_min
INFO:Neuron:aten::grid_sampler
INFO:Neuron:aten::index
INFO:Neuron:aten::nonzero
INFO:Neuron:98.52% of all operations (including primitives) (599 of 608) are supported
INFO:Neuron:92.62% of arithmetic operations (113 of 122) are supported
INFO:Neuron:There are 9 ops of 5 different types in the TorchScript that are not compiled by neuron-cc: aten::clamp_min, aten::grid_sampler, aten::index, aten::nonzero, aten::__or__,
```
so, my model is compiled only 45% of arithmetic operators.
even that I could got a compiled model, but when I tried to inference with that, some errors were occurred.

So I want to add not supported operators when compiling.
I saw some kind of solution from [Issues](https://github.com/aws-neuron/aws-neuron-sdk/issues/630#issuecomment-1439706562), but I don't know which file I need to modify.

Is there someone who used custom operators when compiling?

**Comment by TheoEnns** [comment]
Hi @3i-MiaHong, we are looking into the issue and will reply back soon.

**Comment by aws-ennst** [comment]
Hi 3i-MiaHong, can you share those errors with us?

**Comment by 3i-MiaHong** [comment]
Hi @aws-ennst , this is the errors.

```
INFO:Neuron:PyTorch to TF conversion failed to resolve function on aten::slice with inputs [<tf.Tensor 'aten_nonzero/Where:0' shape=(?, 2) dtype=int64>, 0, 0, 9223372036854775807, 1]
INFO:Neuron:Exception = Cannot convert an unknown Dimension to a Tensor: ?
WARNING:Neuron:torch.neuron.trace failed on _NeuronGraph$164; falling back to native python function call
ERROR:Neuron:Cannot convert an unknown Dimension to a Tensor: ?
Traceback (most recent call last):
  File "/opt/conda/envs/trace-super-update/lib/python3.8/site-packages/torch_neuron/convert.py", line 413, in op_converter
    neuron_function = self.subgraph_compiler(
  File "/opt/conda/envs/trace-super-update/lib/python3.8/site-packages/torch_neuron/decorators.py", line 81, in trace
    transform_torch_graph_to_tensorflow(jit_trace, example_inputs, separate_weights=separate_weights, neuron_graph=func, **kwargs)
  File "/opt/conda/envs/trace-super-update/lib/python3.8/site-packages/torch_neuron/decorators.py", line 634, in transform_torch_graph_to_tensorflow
    raise e
  File "/opt/conda/envs/trace-super-update/lib/python3.8/site-packages/torch_neuron/decorators.py", line 628, in transform_torch_graph_to_tensorflow
    tensor_outputs = local_func(op, *tensor_inputs)
  File "/opt/conda/envs/trace-super-update/lib/python3.8/site-packages/torch_neuron/ops/aten.py", line 2370, in slice
    return tf_slice(tensor, dim, start, end, step)
  File "/opt/conda/envs/trace-super-update/lib/python3.8/site-packages/torch_neuron/ops/aten.py", line 2401, in tf_slice
    max_ind = tf.convert_to_tensor(shape[dim], dtype=end.dtype)
  File "/opt/conda/envs/trace-super-update/lib/python3.8/site-packages/tensorflow_core/python/framework/ops.py", line 1184, in convert_to_tensor
    return convert_to_tensor_v2(value, dtype, preferred_dtype, name)
  File "/opt/conda/envs/trace-super-update/lib/python3.8/site-packages/tensorflow_core/python/framework/ops.py", line 1237, in convert_to_tensor_v2
    return internal_convert_to_tensor(
  File "/opt/conda/envs/trace-super-update/lib/python3.8/site-packages/tensorflow_core/python/framework/ops.py", line 1297, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/opt/conda/envs/trace-super-update/lib/python3.8/site-packages/tensorflow_core/python/framework/constant_op.py", line 335, in _dimension_tensor_conversion_function
    raise ValueError("Cannot convert an unknown Dimension to a Tensor: %s" % d)
ValueError: Cannot convert an unknown Dimension to a Tensor: ?
```

**Comment by aws-ennst** [comment]
Currently we don't support dynamic shapes outputs in aten::nonzero, aten::index, aten::where. Please see https://awsdocs-neuron.readthedocs-hosted.com/en/latest/general/arch/neuron-features/dynamic-shapes.html.

**Comment by 3i-MiaHong** [comment]
Hi @aws-ennst , thank you for replying.

Is There any plan to support those operators for Inf1?

and no matter I change the torch_neuron package code or not, it's not possible to use those operators for NeuronCore-v1 for now?
cause I want to make it sure. Whether compiling could be work or not, when if I update package code.

**Comment by mrnikwaws** [comment]
HI @3i-MiaHong,

In terms of dynamic shape operators (like nonzero) we do have plans to support these on our roadmap: https://github.com/aws-neuron/aws-neuron-sdk/issues/564, however this is for torch-neuronx which does not support inf1.  The short answer then is likely to be 'no' for inf1, this might change with customer demand, but hardware limitations makes it unlikely in my view.

Having said that you should check if dynamic operators are needed in your model.  In some cases (e.g. where nonzero is used to compute which indices to copy or mutate) you can instead create a fixed size boolean mask - e.g. https://pytorch.org/docs/stable/generated/torch.ne.html and then use the where operator to merge two tensors i.e. torch.where(condition, input, other) - *not* torch.where(condition).  This works if you have a fixed shape -> dynamic shape -> fixed shape transition in your model using these operators.

These are fixed shape operators (though I believe we only have partial `where` support on inf1, so you will need to check if you are running a supported usage - i.e. with fixed input / output shapes).  

For variable shape input and output tensors we have successfully used fixed sizes with padding to allow overall dynamic shapes, and then compiled different quantized input / output tensor shapes so that we can 'bin' incoming tensors to the best match.  If you are dealing with long sequence lengths I would recommend looking at inf2 and related examples.

**Comment by aws-mvaria** [comment]
Hi @3i-MiaHong ,
Checking in on whether there was anything else you needed help with. Again, note that [#564](https://github.com/aws-neuron/aws-neuron-sdk/issues/564) is our open roadmap item for dynamic shape support.
Thanks.

**Comment by jeffhataws** [comment]
Hi @3i-MiaHong , we just want to let you know that clamp_min support was added in SDK 2.13 release which will increase the percentage supported operators. The other operators are current unsupported per the note from @mrnikwaws above. We will close this ticket but please let us know if you will need further support. Thanks!
