### ISSUE TITLE
Using multiple LoRAs with the same model.

### ISSUE THREAD

**Issue by gonzachiar** [aws-neuron/aws-neuron-sdk#769]
I compiled the U2-Net from Stable Diffusion XL using torch-neuronx and it's working fine. Also, I trained some LoRAs for that exact model and know I want to have different models withe de different LoRAs. Is there a way I can do this without comiling different U2-Nets, but just use the same one and only swap the LoRAs?

I think a more general way to ask this is: When I load a torch model, I can easily change any part of the model just changing the state_dict, is there a way to imitate this with neuron compiled models?

**Comment by micwade-aws** [comment]
>When I load a torch model, I can easily change any part of the model just changing the state_dict, is there a way to imitate this with neuron compiled models?

No.  If the model is changed, it will need to be recompiled.  You can change it before compiling, but once it's compiled, then any new change will require a recompile.

**Comment by mrnikwaws** [comment]
Closing ticket, since it is answered and no further questions.

**Comment by MrD005** [comment]
@gonzachiar can you help in the steps how you compile SDXL lora on inferentia2

**Comment by gonzachiar** [comment]
@MrD005 if you already did a SDXL deploy, you should be able to just do the lora swapping and then compiling that new UNET like normal.

**Comment by MrA0505** [comment]
Hi @gonzachiar, I'm also facing the same issue <regarding swapping LoRA and then compiling the new UNET like normal>. I'm having difficulty understanding this part because if we fine-tune LoRA Adaptation and compile it like normal, it also generates three .pt models. If I could find a reference link or an example file, it would be helpful. I've used the reference link provided below to train the base model.
https://github.com/aws-neuron/aws-neuron-samples/blob/master/torch-neuronx/inference/hf_pretrained_sdxl_base_1024_inference.ipynb(url)

**Comment by gonzachiar** [comment]
@MrA0505 if you follow this tutorial you will end up with three models:

- The VAE decoder
- The UNet
- The VAE_post_quant_conv

Is most likely that the LoRAs you are training are only part of the UNet model, so the VAE decoder and the VAE_post_quanc_conv should remain the same. So you just need to compile the UNet with the trained LoRA on it and use that in the SDXL pipeline.

**Comment by MrA0505** [comment]
@gonzachiar, thanks for quick response, i will implement this.
