### ISSUE TITLE
Error in running: pip install -r requirements.txt 

### ISSUE THREAD

**Issue by peymanbr** [aws-neuron/aws-neuron-sdk#784]
I'm trying to build the repo on an Ubuntu22.04 machine with Python 3.10.12, and I get the bellow error when I run: `pip install -r requirements.txt `

```
error: Command "x86_64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DNPY_INTERNAL_BUILD=1 -DHAVE_NPY_CONFIG_H=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -D_LARGEFILE64_SOURCE=1 -Ibuild/src.linux-x86_64-3.10/numpy/core/src/umath -Ibuild/src.linux-x86_64-3.10/numpy/core/src/npymath -Ibuild/src.linux-x86_64-3.10/numpy/core/src/common -Inumpy/core/include -Ibuild/src.linux-x86_64-3.10/numpy/core/include/numpy -Inumpy/core/src/common -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/usr/include/python3.10 -Ibuild/src.linux-x86_64-3.10/numpy/core/src/common -Ibuild/src.linux-x86_64-3.10/numpy/core/src/npymath -c build/src.linux-x86_64-3.10/numpy/core/src/multiarray/scalartypes.c -o build/temp.linux-x86_64-3.10/build/src.linux-x86_64-3.10/numpy/core/src/multiarray/scalartypes.o -MMD -MF build/temp.linux-x86_64-3.10/build/src.linux-x86_64-3.10/numpy/core/src/multiarray/scalartypes.o.d -std=c99" failed with exit status 1
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for numpy
      Failed to build numpy
      ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects
```
I tried gcc combinations of versions 10.5.0 and 11.4.0, and numpy versions 1.21.5 and 1.26.1 and got the same error message.

**Comment by jluntamazon** [comment]
Hello,

The main problem you are encountering is that you are not downloading the pre-compiled `numpy` wheels from [pypi.org](http://pypi.org/). You should not have to compile `numpy` manually since the wheels for this should already be available here:
https://pypi.org/project/numpy/1.26.1/#files

One reason why this may be occurring is because the default version of `python` used by `pip` may be an different than your expectation. It is possible that you are attempting to install the most recent `numpy` package with a very old `python` that is no longer supported. To start, I would try explicitly specifying the `python` version in the installation command and using the latest version of `pip`:
```
python3.10 -m pip install numpy==1.26.1
```

A piece of data that would allow us to more easily validate the core problem would be to see the versions of `python` & `pip`:
```
pip --version
python3 --version
python3.10 --version
```

Lastly, including the full installation logs may give us more visibility into why the installation issue is occurring

**Comment by peymanbr** [comment]
Hello,

Thank you for your reply.

I attached the whole printout for the installation.
[pip_install_requirements_error.txt](https://github.com/aws-neuron/aws-neuron-sdk/files/13279492/pip_install_requirements_error.txt)

I uninstalled numpy using `pip uninstall numpy` and installed the suggested version using `python3.10 -m pip install numpy==1.26.1`, but I still get the errors.

The Python and pip versions that I have on my setup are:
```
> pip --version
   pip 22.0.2 from /usr/lib/python3/dist-packages/pip (python 3.10)
> python3 --version
   Python 3.10.12
> python3.10 --version
   Python 3.10.12
```
I noticed that there is still `numpy` version `1.21.5 `that is accessible from Python REPL:
```
$ python
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> print(np.__version__)
1.21.5
>>> 
```
This `numpy` package is placed under: `/usr/lib/python3/dist-packages/`. Perhaps I have to remove it first, and then try the installation process with the required `numpy` release?

**Comment by aws-rhsoln** [comment]
If you are looking for setting up the env for running training/inference, can you try setting it up using the instructions here: https://awsdocs-neuron.readthedocs-hosted.com/en/latest/frameworks/torch/index.html#pytorch-neuronx-main

We think that the issue might be because the numpy version might be having conflict with other packages in this requirements.txt: https://github.com/aws-neuron/aws-neuron-sdk/blob/e7e2245ef85e9e88131baf2e5347658d19107297/requirements.txt

However, the dependencies listed in this requirements.txt are *exclusively* used for building the documentation. For normal usage of Neuron, refer to the readthedocs guides above for installation instructions.

**Comment by peymanbr** [comment]
I think it shouldn't be that hard to build the docs locally. I want to create a PR, and I have to first make sure my changes render as they should.
