### ISSUE TITLE
neuron scheduler extension on EKS is failing

### ISSUE THREAD

**Issue by debajyoti-truefoundry** [aws-neuron/aws-neuron-sdk#796]
[I am following this guide.](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/containers/kubernetes-getting-started.html)

Image: `public.ecr.aws/neuron/neuron-scheduler:2.18.3.0` Also tried with (`public.ecr.aws/neuron/neuron-scheduler:2.16.18.0`)

```
2023/11/24 14:40:03 http: panic serving 10.2.37.164:54286: runtime error: invalid memory address or nil pointer dereference
goroutine 74 [running]:
net/http.(*conn).serve.func1(0xc0002a00a0)
	/usr/local/go/src/net/http/server.go:1824 +0x153
panic(0x12c97c0, 0x1d85410)
	/usr/local/go/src/runtime/panic.go:971 +0x499
container/pkg/scheduler.Filter(0xc0002b31e0, 0xc0004d4800, 0xc0002a2620, 0x0, 0x1)
	/opt/workspace/KaenaContainerRelease/build/private/build/SRC_CPY/pkg/scheduler/filter.go:56 +0x5a
main.filterHandler(0x15c8110, 0xc000460000, 0xc000244300, 0x0, 0x0, 0x0)
	/opt/workspace/KaenaContainerRelease/build/private/build/SRC_CPY/cmd/k8s-neuron-scheduler/routes.go:44 +0x825
github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc00031ba40, 0x15c8110, 0xc000460000, 0xc000244300)
	/go-mod-cache/github.com/julienschmidt/httprouter@v1.3.0/router.go:387 +0xc7e
net/http.serverHandler.ServeHTTP(0xc0001b4540, 0x15c8110, 0xc000460000, 0xc000244300)
	/usr/local/go/src/net/http/server.go:2887 +0xa3
net/http.(*conn).serve(0xc0002a00a0, 0x15c96a0, 0xc000772000)
	/usr/local/go/src/net/http/server.go:1952 +0x8cd
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3013 +0x39b
```

**Comment by james-aws** [comment]
@debajyoti-truefoundry Can you provide details about your cluster setup? 

- what version of kubernetes and eks are you using?
- what node(s) and instance types are in your node group? 
- what ami is used for your node(s)

**Comment by james-aws** [comment]
@debajyoti-truefoundry this crash will be fixed in the next release of the neuron-scheduler. This should be available within two weeks. However the **main issue** is that the scheduler is not finding nodes in your cluster. So there appears to be a configuration issue with your cluster. Please make sure that you are able to deploy a simple workload with the single neuron-device. This will not require the neuron-scheduler, only the k8s-neuron-device-plugin. The neuron-scheduler is only used when requesting a contiguous set of multiple devices. If you are able to deploy the simple workload and still encountering issues with the scheduler, please reach out again.
