### ISSUE TITLE
Compatibility with xformers

### ISSUE THREAD

**Issue by TommasoBendinelli** [aws-neuron/aws-neuron-sdk#847]
The title sums it up all, can I sue the xformers library with Neuron?

**Comment by mrnikwaws** [comment]
Hi @TommasoBendinelli,

I am assuming you mean: https://github.com/facebookresearch/xformers/tree/main ?

Looking at the code base, in particular https://github.com/facebookresearch/xformers/tree/main/xformers/csrc I see that this code base is building custom CUDA and CPU kernels which it is registering with torch runtime to get the promised speed up.  In other words the optimization is for these hardware targets.  

The CUDA kernels definitely won't work on a trn1 or inf2 instance (since we don't use Nvidia hardware on AWS Neuron instance types).  You could try using some of the CPU kernels (i.e manually segment your model on an inf2/trn1 instance), but this would also likely not make your models run faster either and I'd recommend against it.

Neuron works a bit differently - it lowers your model graph to a compiler that attempts to automatically optimize the graph, operator fusions etc.  We also have some hand optimized models we vend in the transformers_neuronx package.

**Comment by mrnikwaws** [comment]
Closing since no more questions in the last week
